// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"videogateway/pkg/api"
	"videogateway/pkg/api/handler"
	"videogateway/pkg/client"
	"videogateway/pkg/config"
)

// Injectors from wire.go:

func InitializeAPI(c *config.Config) (*api.Server, error) {
	videoServiceClient, err := client.InitClient(c)
	if err != nil {
		return nil, err
	}
	videoClient := client.NewVideoClient(videoServiceClient)
	videoHandler := handler.NewVideoHandler(videoClient)
	server, err := api.NewServeHTTP(c, videoHandler)
	if err != nil {
		return nil, err
	}
	return server, nil
}
